version: "3.9"  # optional since v1.27.0
services:
    container01:
        image: "httpd"
        container_name: webserver
        hostname: apache
        ports:             # port mapping
            - "80:80"
        volumes:           # volume mapping
            - /tmp:/data
    container02:
        image: "vijayprabhu04/my_application_image"
        container_name: dependent
        hostname: dependent
        volumes:
            - /tmp:/data
    container03:
        image: "ubuntu"
        container_name: monitoring
        hostname: monitoring
        volumes:
            - /tmp:/data
