apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: LoadBalancer
  selector:
    app: apache
    env: dev
    tag: lb-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30008 # optional if not assigned it will take random port